services:
  - type: web
    name: fastapi-app
    env: docker
    repo: https://github.com/Haneull-dv/haneull-fast.git
    region: singapore
    plan: free
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /